In [5]:
import numpy as np

In [8]:
my_list = [0,1,2,3,4,5,6,7,8,9,10]
nparr = np.array(my_list)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [15]:
nparr = np.arange(0,11) #11이전까지

In [16]:
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
nparr_added = nparr+nparr  #배열의 값들 더함
print(nparr_added)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [19]:
nparr_sub = nparr-nparr
print(nparr_sub)

[0 0 0 0 0 0 0 0 0 0 0]


In [20]:
nparr_mult = nparr * nparr
print(nparr_mult)

[  0   1   4   9  16  25  36  49  64  81 100]


In [21]:
nparr_div = nparr / nparr
print(nparr_div)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-21-ac3be0a7341d>:1: RuntimeWarning: invalid value encountered in true_divide
  nparr_div = nparr / nparr


In [23]:
nparr_esc = nparr * 10 #각 원소에 곱하기 10
print(nparr_esc)

[  0  10  20  30  40  50  60  70  80  90 100]


In [24]:
nparr_one_div = 1/nparr
print(nparr_one_div)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


<ipython-input-24-3d17f1fc195b>:1: RuntimeWarning: divide by zero encountered in true_divide
  nparr_one_div = 1/nparr


In [26]:
nparr_max = np.max(nparr) #최대값 도출
print(nparr_max)

10


In [28]:
nparr_min = np.min(nparr)
print(nparr_min)

0


In [30]:
arr_10to50 = np.arange(10,51)
print(arr_10to50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [34]:
arr_10to50_even = np.arange(10,51,2) #10부터 50까지 2씩 증가 for(i = 10 i<51; i+=2)
print(arr_10to50_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [37]:
np.arange(1,10).reshape(3,3) #1부터 9까지 3*3행렬을 만듬

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.random.randn(1)

array([0.57548171])

In [45]:
np.random.randn(25) #25가지의 랜덤값이 도출

array([-0.95922389,  1.29200764, -0.86504128,  1.32473798,  0.06051864,
       -0.70717937, -1.06405436, -0.61494146, -0.72213361,  0.18142008,
        1.15297771, -1.36937199, -0.93901298, -0.51955794, -0.13730785,
        2.02654846, -1.09896979, -0.75470096, -0.57582317, -1.07418499,
        0.76737886,  0.13156064,  0.46226979, -1.1982236 , -0.84658109])

In [47]:
np.arange(1,101).reshape(10,10)/100 #10*10배열의 값을 100으로 나눔

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [50]:
arr_2_d = np.arange(1,26).reshape(5,5)
print(arr_2_d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [51]:
arr_2_d[3,4]

20

In [53]:
arr_2_d[:3,1:2] #3행 1열만

array([[ 2],
       [ 7],
       [12]])

In [56]:
arr_2_d[4,:] #4행을 모두 

array([21, 22, 23, 24, 25])

In [59]:
np.sum(arr_2_d) #배열안 모든 원소의 값을 더함

325

In [60]:
np.std(arr_2_d)

7.211102550927978

In [68]:
arr_2_d.std() #std = 표준편차

7.211102550927978

In [66]:
arr_2_d.sum(axis=0)

array([55, 60, 65, 70, 75])

In [67]:
arr_2_d.sum(axis=1)

array([ 15,  40,  65,  90, 115])